#Whenever these type of runtime error occur, Python creates an exception object.
#If not handled properly, it prints a traceback to that error along with some details about why that error occurred.
print(locals()['__builtins__'])
#? Write the Exceptions Here